version: 2
jobs:
  build:
    parallelism: 3
    docker:
      - image: circleci/ruby:2.5-node-browsers
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: derby-checkin
          RAILS_ENV: test
      - image: circleci/postgres:10-alpine
        environment:
          POSTGRES_USER: derby-checkin
          POSTGRES_DB: derby-checkin_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout

      # Which version of bundler?
      - run:
          name: Which bundler?
          command: bundle -v

      # Restore bundle cache
      - restore_cache:
          keys:
            - derby-checkin-bundle-{{ checksum "Gemfile.lock" }}
            - derby-checkin-bundle-

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      # Store bundle cache
      - save_cache:
          key: derby-checkin-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Only necessary if app uses webpacker or yarn in some other way
      - restore_cache:
          keys:
            - derby-checkin-yarn-{{ checksum "yarn.lock" }}
            - derby-checkin-yarn-

      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn

      # Store yarn / webpacker cache
      - save_cache:
          key: derby-checkin-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database setup
          command: bin/rails db:schema:load --trace

      - type: shell
        command: |
          bundle exec rails test

      # Save test results for timing analysis
      - store_test_results:
          path: test_results
