default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: derby-checkin_development

test:
  <<: *default
  database: derby-checkin_test

production:
  <<: *default
  database: derby-checkin_production
  username: derby-checkin
  password: <%= ENV['DERBY-CHECKIN_DATABASE_PASSWORD'] %>
